### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by chrisgartsen** [chrisgartsen/declare#12]
### Todo

- [ ] RSpec feature for edit user
- [ ] Edit user form view
- [ ] Update user controller method
