### ISSUE TITLE
Payment Type

### ISSUE THREAD

**Issue by chrisgartsen** [chrisgartsen/declare#13]
## Todo

- [x] RSpec feature for adding payment types
- [x] RSpec feature for editing payment types
- [x] RSpec feature for deleting payment types
- [x] RSpec feature for showing payment types

**Comment by chrisgartsen** [comment]
Completed
