### ISSUE TITLE
Currencies

### ISSUE THREAD

**Issue by chrisgartsen** [chrisgartsen/declare#15]
## TODO

- [ ] Add currency feature
- [ ] Edit currency feature
- [ ] View currency feature
- [ ] Delete currency feature
